# Convenience shorthands.
[alias]
build-ios = ["build", "--target", "x86_64-apple-ios"]
build-android = ["build", "--target", "x86_64-linux-android"]

# Linker configuration settings.
[target.x86_64-apple-ios]
rustflags = [
  "-C", "link-arg=-isysroot", "-C", "link-arg=$(xcrun --sdk iphoneos --show-sdk-path)",
  "-C", "link-arg=-arch", "-C", "link-arg=x86_64",
  "-C", "link-arg=-mios-version-min=10.0"
]

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "x86_64-linux-android-ar"

[build]
target-dir = "modules/rsmod/target"
